# Generated by Django 3.1.4 on 2020-12-26 11:07

import actual.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_name', models.CharField(max_length=144)),
            ],
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=144)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actual.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=144)),
                ('npc_sprite', models.ImageField(height_field=40, upload_to=actual.models.npc_sprite_dir, width_field=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Toon',
            fields=[
                ('toon_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('toon_name', models.CharField(max_length=144)),
                ('toon_sprite', models.ImageField(height_field=40, upload_to=actual.models.toon_sprite_dir, width_field=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actual.user')),
            ],
        ),
        migrations.CreateModel(
            name='MarchOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_x', models.IntegerField()),
                ('pos_y', models.IntegerField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actual.campaign')),
                ('toon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actual.toon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GridObject',
            fields=[
                ('pos_x', models.IntegerField()),
                ('pos_y', models.IntegerField()),
                ('go_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actual.grid')),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actual.npc')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EncounterEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('object_uuid', models.UUIDField()),
                ('action', models.JSONField()),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actual.encounter')),
            ],
        ),
        migrations.AddField(
            model_name='encounter',
            name='grid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actual.grid'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='dm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actual.user'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actual.encounter'),
        ),
    ]
